config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'homes/about'
  root to: 'homes#top'
  devise_for :users
  resources :posts do
    # いいねとコメントはpostモデルにネスト
    resource :favorites,only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    # relationshipsは中間テーブルなので,userモデルにネスト
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  
  get '/search', to: 'searchs#search'

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォロー機能を作成・保存・削除(userモデルで定義したfollow,unfollowメソッドを使用)
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
    # 遷移前のURLを取得
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー・フォロワー一覧の表示
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
    # これでフォローしているユーザid一覧を取得
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
    # これでフォローされているユーザid一覧を取得
  end

  private
    def set_user
      @user = User.find(params[:id])
    end



end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/followers.html.erb
<h1>フォロワー一覧</h1>
<% if @users.exists? %>
  <tbody>
    <% @users.each do |user|%>
      <th><%= user.name %></th>
      <th><%= link_to 'ユーザー詳細画面', user_path(user.id) %></th>
    <% end %>
  </tbody>
<% else %>
  <p>フォロワーはいません</p>
<% end %>
<%= link_to '戻る', :back %>

app/views/relationships/followings.html.erb
<h1>フォロー一覧</h1>
  <% if @users.exists? %>
    <tbody>
      <% @users.each do |user|%>
        <th><%= user.name %></th>
        <th><%= link_to 'ユーザー詳細画面', user_path(user.id) %></th>
      <% end %>
    </tbody>
  <% else %>
    <p>フォローしている人はいません</p>
  <% end %>

  <%= link_to '戻る', :back %>