config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'homes/about'
  root to: 'homes#top'
  devise_for :users
  resources :posts do
    # いいねとコメントはpostモデルにネスト
    resource :favorites,only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    # relationshipsは中間テーブルなので,userモデルにネスト
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  
  get '/search', to: 'searchs#search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  # 投稿との関係

  has_many :post_comments, dependent: :destroy
  #投稿へのコメントとの関係

  has_many :favorites, dependent: :destroy
  attachment :image
  # refileを使用するため記述

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # Relationshipにuser_idカラムはないため、foreign_keyでどのカラムを参照するか定義。見分けやすいようにreverseと定義
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # throughを経由してuserテーブルを参照する  followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  # throughを経由してuserテーブルを参照する  follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

  # いいね機能と同様


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.posts.page(params[:page]).reverse_order
    # すべての投稿画像が表示されないように設定し、全体の投稿ではなく、個人が投稿した物のみ
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)

  end

  def index
    @user = current_user
    @users = User.page(params[:page])
    # User.allでは1ページにすべて出てしまうので登録順に変更
    @post = Post.new
    @posts = Post.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% users.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= user.name %><br>
  <% end %>
<% end %>

app/views/users/_info.html.erb
  <!--フォロー機能-->
  <% if current_user.followings?(user) %>
  <!--フォローしているかどうかを判別-->
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger btn-lg" %>
    <!--フォローしているなら解除-->
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-primary btn-lg"  %>
    <!--フォローしていないならフォローする-->
  <% end %>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">名前</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <%= attachment_image_tag @user, :image, :fill, 60, 60 %>
  <label for="inputName">イメージ画像</label>
  <%= f.attachment_field :image, placeholder: "プロフィール画像" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div class="container">
  <div class="row">
    <% @users.each do |user| %>
      <li class="card col-md-9 offset-md-1" style="margin-top: 10px; padding-bottom: 10px; padding-top: 10px; margin-bottom: 10px;">
        <%= link_to user_path(user.id) do%>
          <br/>
          <!--写真を枠内に入れるためにbr/を使用-->
          <%= attachment_image_tag user, :image, class: "card-img-top "  %>
          <p></p>
          <!--写真と名前の間をあける-->
          <p class="name"><%= user.name %></p>
        <% end %>
      </li>
    <% end %>

  </div>
</div>
<%= paginate @users %>

app/views/users/show.html.erb
<h1>ユーザーページ</h1>
<div class="container container-m">
  <div class="row">

    <div class='col-md-3' style="padding: 0;">
    <div class="profile-container">
      <h3 class="profile-name"><%= @user.name %></h3>
      <br/>
      <br/>
      <%= attachment_image_tag @user, :image, size: "100x100" %>
      <br/>
      <br/>
      <% if @user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success btn-lg" %></p>
      <% end %>
      <br/>
      <br/>
    </div>
    <%= render 'users/info', user: @user %><br/><br/>
    <%= link_to "フォロー一覧", user_followings_path(@user), class: "btn btn-primary btn-lg" %><br/><br/>
    <%= link_to "フォロワー一覧", user_followers_path(@user), class: "btn btn-primary btn-lg" %><br/><br/>
    <li>
    <%= link_to "お問い合わせ", contacts_new_path, class: 'btn btn-primary btn-lg' %>
    </li>
    </div>
       <div class="row col-md-9">
        <% @post_images.each do |post| %>
          <div class="card col-md-9 offset-md-1" style="margin-top: 10px; padding-bottom: 10px; padding-top: 10px; margin-bottom: 10px;">
            <%= link_to post_path(post.id), class: 'card-img-top' do %>
              <%= attachment_image_tag post, :image, :fill, 60, 60 %>
              <p class="card-title">
                ユーザ名:<br/>
                <%= post.user.name %>
              </p>
              <!--変数内のuser_idに関連付けられているuserモデルのnameカラムを表示-->
              <!--<p>ユーザー画像:<br/>-->
              <!--  <%= attachment_image_tag post.user, :image, :fill, 60, 60 %>-->
              <!--#</p>-->
              <p class="card-title">
                投稿タイトル:<br/>
                <%= post.title%>
              </p>
              <!--変数内のtitleを表示-->
              <p class="card-text">
                コメント:<br/>
                <%= post.body %>
              </p>
              <p>
                投稿日：<br/>
                <%= post.created_at.strftime('%Y/%m/%d') %>
              </p>
              <!--変数内のbodyを表示-->
              <!--<a href="../posts/show" class="btn btn-dark">詳細</a>-->
            <% end %>
          </div>
        <% end %>
      </div>
  </div>
</div>

<%= paginate @post_images %>