config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'homes/about'
  root to: 'homes#top'
  devise_for :users
  resources :posts do
    # いいねとコメントはpostモデルにネスト
    resource :favorites,only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    # relationshipsは中間テーブルなので,userモデルにネスト
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  
  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
                    #メールアドレスが有効かどうか判別する
  validates :contact, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  # コメント機能との関係
  has_many :favorites, dependent: :destroy
  # お気に入り機能との関係
  attachment :image
  # 画像アップ用のメソッド追加（refileのルール）
  validates :title, presence: true
  validates :body, presence: true
  # バリデーション　上記のカラムが入っていないと戻る
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    #このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在するか確認
  end

#ランキング機能作成のため作成 
  def self.create_all_ranks #postクラスからデータを取ってくる処理なのでクラスメソッド
    Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    # favorite.group(:post_id)      投稿の番号が同じものになるグループを分ける
    # order('count(post_id) desc')  番号の多い順に並べ替える
    # limit(3)                      表示する物の数
    # pluck(:post_id)               post_idカラムのみを数字で取り出す

    # Post.find()                   pluckで取り出される数字をpost_idにすることでいいね順にpostを取得できる
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  # 投稿との関係

  has_many :post_comments, dependent: :destroy
  #投稿へのコメントとの関係

  has_many :favorites, dependent: :destroy
  attachment :image
  # refileを使用するため記述

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # Relationshipにuser_idカラムはないため、foreign_keyでどのカラムを参照するか定義。見分けやすいようにreverseと定義
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # throughを経由してuserテーブルを参照する  followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  # throughを経由してuserテーブルを参照する  follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

  # いいね機能と同様


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to thanks_contacts_path
    else
      render :new
    end
  end

  def thanks
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :email, :contact)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    # redirect_to post_path(post) ←非同期にするために削除
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    # redirect_to post_path(post) ←非同期にするために削除
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @post = Post.new
    # 新しい投稿
    # @posts = Post.all
    # すべての投稿
    @posts = Post.page(params[:page]).reverse_order
    # Post.allでは1ページにすべて出てしまうので、「指定の数だけ。新しいもの順」に変更
    @all_ranks = Post.create_all_ranks
    # modelで作成した物を使用
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # ユーザーと投稿を紐づけ
     if @post.save
      redirect_to posts_path
     else
      @posts = Post.page(params[:page]).reverse_order
      render :index
     end
    # 情報を保存
  end

  def edit
    @post = Post.new
    # 新規作成用
    @post = Post.find(params[:id])
    # postモデルのデータベースから投稿データを取得
  end

  def update
    # post = Post.find(params[:id])
    # post.update(post_params)
    # if post.user == current_user
    #   redirect_to user_path(current_user.id)
    # else
    #   render "index"
    # end
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def show
    @post = Post.find(params[:id])
    # 主キーに対応するレコードを取り出す
    @post_comment = PostComment.new
    # 新しいコメント
  end

  def destroy
    @post = Post.find(params[:id])
    # 主キーに対応するレコードを取り出す
    @post.destroy
    redirect_to posts_path
  end



  private
  # 投稿データのストロングパラメータ
  def post_params
    params.require(:post).permit(:user_id, :title, :image, :body)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path
    end
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    # viewのform_tagで選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入したsearch_forを@recordsに代入。
    @records = search_for(@model, @method, @content)
  end

  private
  def search_for(model, method, content)
    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        User.where(name: content)
      # 選択した検索方法がが部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがpostだったら
    elsif model == 'post'
      if method == 'perfect'
        Post.where(title: content)
      else
        Post.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.posts.page(params[:page]).reverse_order
    # すべての投稿画像が表示されないように設定し、全体の投稿ではなく、個人が投稿した物のみ
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)

  end

  def index
    @user = current_user
    @users = User.page(params[:page])
    # User.allでは1ページにすべて出てしまうので登録順に変更
    @post = Post.new
    @posts = Post.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="topbody">
    <h1>～サイト概要～</h1>
    <%= image_tag 'image2.png', class:'img' %>

    <p>このアプリは0～6歳の子供を育てている人をターゲットにした、twitterのような感じで個人で情報を上げれるサイトです。<br/>
        今まで子育てをしてきた人や現在進行形で子育てをしている人が様々な価値観や思ったことを好きに書き込めます。 <br/>
        書き込んでもらうことで、「この年齢の時にこんなグッズが役に立った」、「こんな風に声掛けをしてみたら子どもがすんなり聞いてくれた」、<br/>
        などの情報を知ることができます。 <br/>
        そうすることで一人でも多くの子育てに不安を抱えている人の手助けになったらいいな、と考えこのサイトを作成しました。<br/>
    </P><br/>
    <p>
        ～このサイトを利用される方へ～
    </p><br/>
    <P>
        子育てに不安を抱えている人や、新しく生まれてくる赤ちゃんに何が必要かわからない時に利用してもらいたいです。
    </P><br/>
    <h3>～注意事項～</h3>
    <P>
        誹謗中傷するようなコメントは書かないでください。
    </P><br/>
</div>

app/views/homes/top.html.erb
<h1 class="text-center">parentingへようこそ！</h1>
  <div id="container">
    <div id="theTarget">
      <div class="test1"></div>
      <div class="test2"></div>
      <div class="test3"></div>
      <div class="test4"></div>
      <div class="test5"></div>
    </div>
  </div>
<p class="text-center">
  このサイトは,新規登録/ログインを行ってからお進みください！<br/>
  登録費は無料となっております。
</p>

<ul class="text-center">
  <li>
    <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  </li>
  <li>
    <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary btn-lg' %>
  </li>
  <li>
    <%= link_to "お問い合わせ", contacts_new_path, class: 'btn btn-primary btn-lg' %>
  </li>
</ul>

app/views/searchs/_form.html.erb
<div class="input is-rounded">
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "ユーザー" => "user", "投稿" => "post" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
      <%= submit_tag '検索', class: "fas fa-search" %>
    <% end %>
<% end %>
</div>

app/views/searchs/search.html.erb
<!--検索結果表示-->
<div class="search-body">
  <% if @model == 'user' %>
    <h3>【Usersモデルの検索結果】検索ワード：<%= @content %></h3>
    <%= render 'users/index', users: @records %>
  <% else @model == 'post' %>
    <h3>【Postsモデルの検索結果】検索ワード：<%= @content %></h3>
    <%= render 'posts/index', posts: @records %>
  <% end %>
</div>