config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'homes/about'
  root to: 'homes#top'
  devise_for :users
  resources :posts do
    # いいねとコメントはpostモデルにネスト
    resource :favorites,only: [:create, :destroy]

    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    # relationshipsは中間テーブルなので,userモデルにネスト
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  
  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
                    #メールアドレスが有効かどうか判別する
  validates :contact, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  # コメント機能との関係
  has_many :favorites, dependent: :destroy
  # お気に入り機能との関係
  attachment :image
  # 画像アップ用のメソッド追加（refileのルール）
  validates :title, presence: true
  validates :body, presence: true
  # バリデーション　上記のカラムが入っていないと戻る
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    #このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在するか確認
  end

#ランキング機能作成のため作成 
  def self.create_all_ranks #postクラスからデータを取ってくる処理なのでクラスメソッド
    Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    # favorite.group(:post_id)      投稿の番号が同じものになるグループを分ける
    # order('count(post_id) desc')  番号の多い順に並べ替える
    # limit(3)                      表示する物の数
    # pluck(:post_id)               post_idカラムのみを数字で取り出す

    # Post.find()                   pluckで取り出される数字をpost_idにすることでいいね順にpostを取得できる
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  # 投稿との関係

  has_many :post_comments, dependent: :destroy
  #投稿へのコメントとの関係

  has_many :favorites, dependent: :destroy
  attachment :image
  # refileを使用するため記述

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # Relationshipにuser_idカラムはないため、foreign_keyでどのカラムを参照するか定義。見分けやすいようにreverseと定義
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # throughを経由してuserテーブルを参照する  followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  # throughを経由してuserテーブルを参照する  follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

  # いいね機能と同様


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @post = Post.new
    # 新しい投稿
    # @posts = Post.all
    # すべての投稿
    @posts = Post.page(params[:page]).reverse_order
    # Post.allでは1ページにすべて出てしまうので、「指定の数だけ。新しいもの順」に変更
    @all_ranks = Post.create_all_ranks
    # modelで作成した物を使用
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # ユーザーと投稿を紐づけ
     if @post.save
      redirect_to posts_path
     else
      @posts = Post.page(params[:page]).reverse_order
      render :index
     end
    # 情報を保存
  end

  def edit
    @post = Post.new
    # 新規作成用
    @post = Post.find(params[:id])
    # postモデルのデータベースから投稿データを取得
  end

  def update
    # post = Post.find(params[:id])
    # post.update(post_params)
    # if post.user == current_user
    #   redirect_to user_path(current_user.id)
    # else
    #   render "index"
    # end
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def show
    @post = Post.find(params[:id])
    # 主キーに対応するレコードを取り出す
    @post_comment = PostComment.new
    # 新しいコメント
  end

  def destroy
    @post = Post.find(params[:id])
    # 主キーに対応するレコードを取り出す
    @post.destroy
    redirect_to posts_path
  end



  private
  # 投稿データのストロングパラメータ
  def post_params
    params.require(:post).permit(:user_id, :title, :image, :body)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path
    end
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    # viewのform_tagで選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入したsearch_forを@recordsに代入。
    @records = search_for(@model, @method, @content)
  end

  private
  def search_for(model, method, content)
    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        User.where(name: content)
      # 選択した検索方法がが部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがpostだったら
    elsif model == 'post'
      if method == 'perfect'
        Post.where(title: content)
      else
        Post.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.posts.page(params[:page]).reverse_order
    # すべての投稿画像が表示されないように設定し、全体の投稿ではなく、個人が投稿した物のみ
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)

  end

  def index
    @user = current_user
    @users = User.page(params[:page])
    # User.allでは1ページにすべて出てしまうので登録順に変更
    @post = Post.new
    @posts = Post.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p class="foot">CopyRight Parenting</p>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
    <div class="container">
      <div class="row">
      <li class="title", style="large">
        <%= link_to "Parenting", root_path %>
      </li>
      <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
        <!--<span class="navbar-toggler-icon"></span>-->
      <!--</button>-->

      <nav class="box float-right mt-5 mb-4">
        <ul>
        <% if user_signed_in? %><!--ログイン済みならばif以下が、ログインしていなければelse以下が表示される-->
          <li class="wrap">
            <!--<a href="#" class="fancy-button bg-gradient1"><span><i class="fa fa-wheelchair-alt"></i>Follow Me</span></a>-->
            <%= link_to "マイページ", user_path(current_user), class:"button" %>
          </li>
          <li>
            <%= link_to "子育て世代一覧", users_path, class:"button" %>
          </li>
          <li>
            <%= link_to "子育て情報", posts_path, class:"button" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, class:"button", method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "ホーム", root_path, class:"button" %>
          </li>
          <li>
            <%= link_to "概要", homes_about_path, class:"button" %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, class:"button" %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path, class:"button" %>
          </li>
        <% end %>
        </ul>
      </nav>
      </div>
      <div class="row float-right mb-3">
        <%= render 'searchs/form' %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parenting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--本家-->
    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--新規-->
    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%#= render 'layouts/header2' %>
    <%= render 'layouts/header' %>
    <br/>
    
    <%= yield %>

   <div class="footer"> 
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>